{% set version = "3.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hdrcde
  version: {{ version|replace("-", "_") }}

source:
  fn: hdrcde_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/hdrcde_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/hdrcde/hdrcde_{{ version }}.tar.gz
  sha256: bc0fd22b7196985bc1ae47b5bcfb2535b4377b9d60261bec77093231c5ab01a4

build:
  number: 0
  # r-ks is not available for win or osx
  skip: true  # [win or osx]

  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
    - r-kernsmooth
    - r-ash
    - r-ks
    - r-locfit
    - r-mvtnorm
    - r-ggplot2
    - r-rcolorbrewer
    - posix                # [win]
    - {{native}}toolchain  # [win]
    - gcc                  # [not win]

  run:
    - r-base
    - r-kernsmooth
    - r-ash
    - r-ks
    - r-locfit
    - r-mvtnorm
    - r-ggplot2
    - r-rcolorbrewer
    - libgcc  # [not win]

test:
  commands:
    - $R -e "library('hdrcde')"  # [not win]
    - "\"%R%\" -e \"library('hdrcde')\""  # [win]

about:
  home: http://www.robjhyndman.com/software/hdrcde
  license: GPL (>= 2)
  summary: Computation of highest density regions in one and two dimensions, kernel estimation
    of univariate density functions conditional on one covariate, and multimodal regression.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
