travis:
  secure:
    BINSTAR_TOKEN: Vh3hMFQ+qi/9c2eXE0+qRcb0qW4TF5ZWtMqm6YgeRhiRAKU6iAM9BgmMAfze8byksOK8RioHSubA5UdxWU24mf4JZsJoZA7LNp/SVJl6zZSIf6ivLAQLFkIGef61hZCZSxbD2F8dHa02QniFV10iit/xwqIG8lanC0XEGKqbEy8g86RF0+I6cNpTOoQdt5wxbdV8L+EEYx9LDdsTxpc/s6MinEbisb7NuxwhnKUmm/1wVkVneAzZIUfgmxN5trLto7pFssjdyXelYEefiIBcHMUnOtXp6cen9NLBRm7+v/HFotZcyQNq/O/wHNOi1CLOY+SAmnNjWar22UwEBQ8/Ym2JIXygOFyZYZB6eMYzI54RYIbJfgn8odzc4Quy6gBlsYlS6YCxFFo/HZ4pPs0T9PmSLnvFBRsQ94qQ4Y46m+OTHYXGVRap6pd6eJfnVt3h/0BX0FL/03pULYWIbf6uY81aJDYLj0LeDTRsB7esvomFMA4qcSpLY1u91O8QfxWhjrjrzNrrl/tV9IqmdgVZNhTRPXuL9BMVChy52w8wEh3YWtlM5hp1jdIf2CZwtITS/DgL1HQ5ImjsuFyYXgpT5iaH0LNFz8mMYy0V7977ttaOTZOKNKgJyb6iCgJuZUr9ZEZYL8UBxCr44vzHyQOYkhITVFTlfZm6r5pJRPqVspA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
